
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app/
    environment:
      - DEBUG=True

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}

volumes:
  postgres_data: