# Generated by Django 5.1.4 on 2025-02-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0009_remove_visitor_achievements_visitor_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
